### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by MLCarey321** [walmart-technology-cps/awesome-board#1]
Add code necessary to add the Digital Awesome Board to a Slack team as a bot. Slack API token needs to be externalized. At some point, if need be, this may be refactored out into its own repo; consequently, additions made specifically to enable Slack integration should be well documented to make future extraction easier.

**Comment by timduan** [comment]
First pull request at https://github.com/walmart-technology-cps/awesome-board/pull/5. 
Finished awesome-board and slack-bot integration. See the updated README-Quick Start-6,7,8,9 for operations commands.
Also all the redundant hubot node_modules in the original packages.json have been removed.

**Comment by MLCarey321** [comment]
PR has been merged, closing this issue. Please open issues for slack functionality that still needs to be implemented.
